version: '3.8'

services:

  mysqldb:
    image: mysql:8.4
    container_name: mysqldb
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_HOST_PORT:$MYSQLDB_CONTAINER_PORT
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      - my-network
    restart: always

  redis:
    image: redis:7.4.1
    container_name: redis
    command: redis-server --appendonly yes
    ports:
      - "${REDIS_HOST_PORT}:${REDIS_CONTAINER_PORT}"
    volumes:
      - redis:/data
    networks:
      - my-network

  node-main:
    image: node:23.1.0-alpine3.19
    container_name: node-main
    env_file:
      - ./.env
    ports:
      - "${NODE_MAIN_HOST_PORT}:${NODE_MAIN_CONTAINER_PORT}"
    command: sh -c "yarn install && yarn run dev && echo 'Main Process Server started on http://localhost:${NODE_MAIN_HOST_PORT}'"
    working_dir: /usr/src/app
    volumes:
      - ./services/main-service/package.json:/usr/src/app/package.json
      - ./services/main-service/:/usr/src/app
      - node-main-node_modules:/usr/src/app/node_modules
    networks:
      - my-network
    restart: always
    depends_on:
      - mysqldb
      - redis

  node-background:
    image: node:23.1.0-alpine3.19
    container_name: node-background
    env_file:
      - ./.env
    ports:
      - "${NODE_BACKGROUND_HOST_PORT}:${NODE_BACKGROUND_CONTAINER_PORT}"
    command: sh -c "yarn install && yarn run dev && echo 'Background Process Server started on http://localhost:${NODE_BACKGROUND_HOST_PORT}'"
    working_dir: /usr/src/app
    volumes:
      - ./services/background-service/package.json:/usr/src/app/package.json
      - ./services/background-service/:/usr/src/app
      - node-background-node_modules:/usr/src/app/node_modules
    networks:
      - my-network
    restart: always
    depends_on:
      - mysqldb
      - redis

volumes:
  redis:
  mysqldb:
  node-main-node_modules:
  node-background-node_modules:

networks:
  my-network:
    driver: bridge
